== perspective_tariff
:hardbreaks-option:

_определение перспективного тарифа для телеком-компании_

===== Цель проекта:

> Мы аналитик компании «Мегалайн» — федерального оператора сотовой связи. Клиентам предлагают два тарифных плана: «Смарт» и «Ультра». Чтобы скорректировать рекламный бюджет, коммерческий департамент хочет понять, какой тариф приносит больше денег.
>
> Нам предстоит сделать предварительный анализ тарифов на небольшой выборке клиентов. В вашем распоряжении данные 500 пользователей «Мегалайна»: кто они, откуда, каким тарифом пользуются, сколько звонков и сообщений каждый отправил за 2018 год. Нужно проанализировать поведение клиентов и сделать вывод — какой тариф лучше.

===== Использовались следующие стек и инструменты при выполнение проекта:
Pandas, Python, Matplotlib, NumPy, SciPy, описательная статистика, проверка статистических гипотез.

===== Вывод:

Средние чеки тарифов смарт и ультра значимо различаются.Выручка от тарифа смарт больше.

Выручка по Москве отличается от других городов.

===== Проект завершен.
