== choosing_well_location
:hardbreaks-option:

_выбор локации для скважины_

===== Цель проекта:

> Для добывающей компании «ГлавРосГосНефть» нужно решить, где бурить новую скважину.
>
> Шаги для выбора локации обычно такие:
>
> 1. В избранном регионе собирают характеристики для скважин: качество нефти и объём её запасов;
> 1. Строят модель для предсказания объёма запасов в новых скважинах;
> 1. Выбирают скважины с самыми высокими оценками значений;
> 1. Определяют регион с максимальной суммарной прибылью отобранных скважин.
>
> Нам предоставлены пробы нефти в трёх регионах. Характеристики для каждой скважины в регионе уже известны. Построем модель для определения региона, где добыча принесёт >наибольшую прибыль. Проанализируйте возможную прибыль и риски техникой Bootstrap.

===== Использовались следующие стек и инструменты при выполнение проекта:
Pandas, Scikit-learn, бутстреп.

===== Вывод:
По полученным данным сделал вывод, и нашел регион котрый больше подходит под цели проекта.

===== Проект завершен.
