== music_of_big_cities
:hardbreaks-option:

_музыка больших городов_

===== Цель проекта:

> Сравнение Москвы и Петербурга окружено мифами:
>
> . Москва — мегаполис, подчинённый жёсткому ритму рабочей недели;
> 
> . Петербург — город своеобразной культуры, непохожий на Москву.
>
> Некоторые мифы отражают действительность. Другие — пустые стереотипы. Бизнес должен отличать первые от вторых, чтобы принимать рациональные решения. На реальных данных Яндекс Музыки мы проверим гипотезы и сравним поведение пользователей двух столиц.
>
> Гипотезы:
>
> . Активность пользователей зависит от дня недели. Причём в Москве и Петербурге это проявляется по-разному.
>
> . Утром в понедельник в Москве преобладают одни жанры музыки, а в Петербурге — другие. Это верно и для вечера пятницы.
>
> . Москва и Петербург предпочитают разные жанры музыки. В Москве чаще слушают поп-музыку, в Петербурге — русский рэп.

===== Использовались следующие стек и инструменты при выполнение проекта:
Pandas, Python.

===== Вывод:

Мы проверили три гипотезы и установили:

. День недели по-разному влияет на активность пользователей в Москве и Петербурге.

. Музыкальные предпочтения не сильно меняются в течение недели — будь то Москва или Петербург. Небольшие различия заметны в начале недели, по понедельникам:

. Во вкусах пользователей Москвы и Петербурга больше общего чем различий. Вопреки ожиданиям, предпочтения жанров в Петербурге напоминают московские.

===== Проект завершен.
