= Yandex Practicum
:hardbreaks-option:

Мною выполнено 15 проектов в рамках обучения, 
проекты выложены как есть, без рефакторинга, 
ниже краткое описание каждого проекта:

=== Исследование данных сервиса “Яндекс.Музыка” — сравнение пользователей двух городов.
xref:./music_of_big_cities/main.ipynb[music_of_big_cities]

_Использовались следующие стек и инструменты при выполнение проекта_: Pandas, Python.

Сравнение Москвы и Петербурга окружено мифами:
Москва — мегаполис, подчинённый жёсткому ритму рабочей недели; 
Петербург — город своеобразной культуры, непохожий на Москву.

Некоторые мифы отражают действительность. Другие — пустые стереотипы. Бизнес должен отличать первые от вторых, чтобы принимать рациональные решения. На реальных данных Яндекс.Музыки мы проверим данные и сравним поведение пользователей двух столиц.   
  
=== Исследование надёжности заёмщиков — анализ банковских данных.
xref:./borrower_reliability_research/main.ipynb[borrower_reliability_research]

_Использовались следующие стек и инструменты при выполнение проекта_: предобработка данных, Pandas, Python.

Заказчик — кредитный отдел банка. Нужно разобраться, влияет ли семейное положение и количество детей клиента на факт погашения кредита в срок. Входные данные от банка — статистика о платёжеспособности клиентов.

Результаты исследования будут учтены при построении модели кредитного скоринга — специальной системы, которая оценивает способность потенциального заёмщика вернуть кредит банку.

=== Продажа квартир в Санкт-Петербурге — анализ рынка недвижимости.
xref:./sale_apartment/main.ipynb[sale_apartment]

_Использовались следующие стек и инструменты при выполнение проекта_: Python, Pandas, Matplotlib, исследовательский анализ данных, визуализация данных, предобработка данных.

В вашем распоряжении данные сервиса Яндекс Недвижимость — архив объявлений о продаже квартир в Санкт-Петербурге и соседних населённых пунктах за несколько лет. Нужно научиться определять рыночную стоимость объектов недвижимости. Ваша задача — установить параметры. Это позволит построить автоматизированную систему: она отследит аномалии и мошенническую деятельность.

По каждой квартире на продажу доступны два вида данных. Первые вписаны пользователем, вторые — получены автоматически на основе картографических данных. Например, расстояние до центра, аэропорта, ближайшего парка и водоёма.

=== Определение выгодного тарифа для телеком компании.
xref:./perspective_tariff/main.ipynb[perspective_tariff]

_Использовались следующие стек и инструменты при выполнение проекта_: Pandas, Python, Matplotlib, NumPy, SciPy, описательная статистика, проверка статистических гипотез.

Проведен предварительный анализ использования тарифов на выборке клиентов, проанализировано поведение клиентов при использовании услуг оператора и рекомендованы оптимальные наборы услуг для пользователей. Проведена предобработка данных, их анализ. Проверены гипотезы о различии выручки абонентов разных тарифов и различии выручки абонентов из Москвы и других регионов.

=== Онлайн магазин.
xref:./online-store/main.ipynb[online-store]

_Использовались следующие стек и инструменты при выполнение проекта_: Pandas, Python, Matplotlib, NumPy.

Мы работаем в интернет-магазине «Стримчик», который продаёт по всему миру компьютерные игры. Из открытых источников доступны исторические данные о продажах игр, оценки пользователей и экспертов, жанры и платформы (например, Xbox или PlayStation). Нам нужно выявить определяющие успешность игры закономерности. Это позволит сделать ставку на потенциально популярный продукт и спланировать рекламные кампании.


=== Классификаиция клиентов телеком компании.
xref:./tariff_recommendation/main.ipynb[tariff_recommendation]

_Использовались следующие стек и инструменты при выполнение проекта_: Pandas, Python, Matplotlib, Scikit-learn.

Оператор мобильной связи выяснил: многие клиенты пользуются архивными тарифами. Они хотят построить систему, способную проанализировать поведение клиентов и предложить пользователям один из новых тариф.

=== Прогнозирование оттока клиента Банка.
xref:./customer_churn/main.ipynb[customer_churn]

_Использовались следующие стек и инструменты при выполнение проекта_: Pandas, Matplotlib, Scikit-learn.

Из банка стали уходить клиенты. Каждый месяц. Немного, но заметно. Банковские маркетологи посчитали: сохранять текущих клиентов дешевле, чем привлекать новых. Нужно спрогнозировать, уйдёт клиент из банка в ближайшее время или нет. Предоставлены исторические данные о поведении клиентов и расторжении договоров с банком.

=== Определение наиболее выгодного региона нефтедобычи.
xref:./choosing_well_location/main.ipynb[choosing_well_location]

_Использовались следующие стек и инструменты при выполнение проекта_: Pandas, Scikit-learn, бутстреп.

Нам предоставлены пробы нефти в трёх регионах. Характеристики для каждой скважины в регионе уже известны. Построем модель для определения региона, где добыча принесёт наибольшую прибыль.

=== Исследование технологического процесса очистки золота.
xref:./recovery_gold_from_ore/main.ipynb[recovery_gold_from_ore]

_Использовались следующие стек и инструменты при выполнение проекта_: Matplotlib, NumPy, Pandas, Python, Scikit-learn, исследовательский анализ данных.

Строится модель машинного обучения для промышленной компании, разрабатывающая решения для эффективной работы промышленных предприятий. Модель должна предсказать коэффициент восстановления золота из золотосодержащей руды на основе данных с параметрами добычи и очистки. Модель поможет оптимизировать производство.

=== Защита данных клиентов страховой компании.
xref:./protection_data_of_clients/main.ipynb[protection_data_of_clients]

_Использовались следующие стек и инструменты при выполнение проекта_: Python, NumPy, Scikit-learn.

Необходимо защитить данные клиентов страховой компании «Хоть потоп». Разработаем такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуем корректность его работы. Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

=== Построение модели определения стоимости автомобиля.
xref:./determination_cost_of_cars/main.ipynb[determination_cost_of_cars]

_Использовались следующие стек и инструменты при выполнение проекта_: Pandas, Python, Lightgbm, Catboost.

Сервис по продаже автомобилей с пробегом разрабатывает приложение для привлечения новых клиентов. На основе исторических данные необходимо построить модель для определения стоимости автомобиля.

=== Прогнозирование количества заказов такси на следующий час.
xref:./forecasting_taxi_orders/main.ipynb[forecasting_taxi_orders]

_Использовались следующие стек и инструменты при выполнение проекта_: Pandas, Python, Scikit-learn, statsmodels.

Компания такси собрала исторические данные о заказах такси в аэропортах. Чтобы привлекать больше водителей в период пиковой нагрузки, нужно спрогнозировать количество заказов такси на следующий час. Строится модель для такого предсказания.

=== Обучение модели классификации комментариев.
xref:./training_comment_classification_model/main.ipynb[training_comment_classification_model]

_Использовались следующие стек и инструменты при выполнение проекта_: Pandas, Python, Nltk, Tf-idf.

Интернет-магазин запускает новый сервис. Теперь пользователи могут редактировать и дополнять описания товаров, как в вики-сообществах. Требуется инструмент, который будет искать токсичные комментарии и отправлять их на модерацию.

=== Обработка фотографий покупателя.
xref:./processing_buyer_photos/main.ipynb[processing_buyer_photos]

_Использовались следующие стек и инструменты при выполнение проекта_: Python, Keras.

Сетевой супермаркет «Хлеб-Соль» внедряет систему компьютерного зрения для обработки фотографий покупателей. Фотофиксация в прикассовой зоне поможет определять возраст клиентов, чтобы:
 1. Анализировать покупки и предлагать товары, которые могут заинтересовать покупателей этой возрастной группы;
 2. Контролировать добросовестность кассиров при продаже алкоголя.
Построем модель, которая по фотографии определит приблизительный возраст человека. В нашем распоряжении набор фотографий людей с указанием возраста.

=== Промышленность Финальный проект.
xref:./industry/main.ipynb[industry]

_Использовались следующие стек и инструменты при выполнение проекта_: предобработка данных, Pandas, Python, matplotlib, Scikit-learn, Catboost.

Чтобы оптимизировать производственные расходы, металлургический комбинат ООО «Так закаляем сталь» решил уменьшить потребление электроэнергии на этапе обработки стали. Нам предстоит построить модель, которая предскажет температуру стали.
