== tariff_recommendation
:hardbreaks-option:

_рекомендация тарифов_

===== Цель проекта:

> Оператор мобильной связи «Мегалайн» выяснил: многие клиенты пользуются архивными тарифами. Они хотят построить систему, способную проанализировать поведение клиентов и предложить пользователям новый тариф: «Смарт» или «Ультра».
>
> В нашем распоряжении данные о поведении клиентов, которые уже перешли на эти тарифы. Нужно построить модель для задачи классификации, которая выберет подходящий тариф. Предобработка данных не понадобится — мы её уже сделали.
>
> Построим модель с максимально большим значением accuracy. Чтобы сдать проект успешно, нужно довести долю правильных ответов по крайней мере до 0.75. Проверим accuracy на тестовой выборке самостоятельно.

===== Использовались следующие стек и инструменты при выполнение проекта:
Pandas, Python, Matplotlib, Scikit-learn.

===== Вывод: 
Константная модель выдает 68%.Наша модель показывает 78%, значит она адекватна.
Лучший Accuracy получился в тестовой выборке в RandomForestClassifier при глубине 10.
Не все гиперпараметры дают большое значение Accuracy.
Итоговый Accuracy получился больше 75%.

===== Проект завершен.
