== online-store
:hardbreaks-option:

_интернет-магазин_  

===== Цель проекта:

> Мы работаем в интернет-магазине «Стримчик», который продаёт по всему миру компьютерные игры. Из открытых источников доступны исторические данные о продажах игр, оценки пользователей и экспертов, жанры и платформы (например, Xbox или PlayStation). Нам нужно выявить определяющие успешность игры закономерности. Это позволит сделать ставку на потенциально популярный продукт и спланировать рекламные кампании.
> 
> Перед нами данные до 2016 года. Представим, что сейчас декабрь 2016 г., и мы планируете кампанию на 2017-й. Нужно отработать принцип работы с данными. Неважно, прогнозируете ли вы продажи на 2017 год по данным 2016-го или же 2027-й — по данным 2026 года.
> 
> В наборе данных попадается аббревиатура ESRB (Entertainment Software Rating Board) — это ассоциация, определяющая возрастной рейтинг компьютерных игр. ESRB оценивает игровой контент и присваивает ему подходящую возрастную категорию, например, «Для взрослых», «Для детей младшего возраста» или «Для подростков».

===== Использовались следующие стек и инструменты при выполнение проекта:
Pandas, Python, Matplotlib, NumPy.

===== Вывод:

. Видим что платформы PS4 и XOne это новые платформы и надо делать упор на них.
. Новые платформы приносят больше денег при меньшем количесте игр.
. В Америке и Европе надо делать упор на экшены и спортивные игры;популярны игры с возрастным ограничением 17+.
. В Японии популярные жанры ролевые игры и экшены;популярны игры с возрастным ограничением 13+

===== Проект завершен.
