== determination cost of cars
:hardbreaks-option:

_определение стоимости автомобилей_

===== Цель проекта:

> Сервис по продаже автомобилей с пробегом «Не бит, не крашен» разрабатывает приложение для привлечения новых клиентов. В нём можно быстро узнать рыночную стоимость своего автомобиля. В вашем распоряжении исторические данные: технические характеристики, комплектации и цены автомобилей. Вам нужно построить модель для определения стоимости.
>
> Заказчику важны:
>
> качество предсказания;
>
> скорость предсказания;
>
> время обучения.

===== Использовались следующие стек и инструменты при выполнение проекта:
Pandas, Python, Lightgbm, Catboost.

===== Вывод:

Мы использовали технологию градиетного бустинга в моделях CatBoostRegressor и LightGBM, и сравнили её с базовыми моделями LinearRegression и RandomForestRegressor. 
Таким образом для компании "Не бит, не крашен" рекомендую модель CatBoostRegressor, т.к. можно немного поступиться со скоростью обучения в пользу достижения скорости работы на новых данных при сохранении приблизительно тех же показателей по качеству предсказания

===== Проект завершен.
