== recovery_of_gold_from_ore
:hardbreaks-option:

_восстановление золота из руды_

===== Цель проекта:

> Восстановление золота из руды
> Подготовим прототип модели машинного обучения для «Цифры». Компания разрабатывает решения для эффективной работы промышленных предприятий.
>
> Модель должна предсказать коэффициент восстановления золота из золотосодержащей руды. Используем данные с параметрами добычи и очистки.
>
> Модель поможет оптимизировать производство, чтобы не запускать предприятие с убыточными характеристиками.

===== Использовались следующие стек и инструменты при выполнение проекта:
Matplotlib, NumPy, Pandas, Python, Scikit-learn, исследовательский анализ данных.

===== Вывод:

. По графикам видно, что грануля сырья в тестовой выборке больше.

. По графикам при подсчете общей концентрации увидили что есть выбросы, при тесте не стали их удалять чтобы не подгонять к лучшему результату.

. Видим что лучше всего себя показала модель sMAPE при линейной регресии 7.042379276247026.

===== Проект завершен.
